# Generated by Django 3.2.7 on 2025-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initial_ID', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Open_End', models.CharField(max_length=1000)),
            ],
        ),
    ]
