# Generated by Django 3.2.7 on 2025-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_data',
            name='Age',
            field=models.CharField(max_length=50),
        ),
    ]
